source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Optik_Example' do
    platform :ios, '12.0'

    pod 'Optik', :path => '../'
    pod 'AlamofireImage', '3.5.2'
end

target 'Optik_Tests' do
    platform :ios, '12.0'

    pod 'Optik', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "12.0"
    end
  end
end
